name: update pharmacy info
on: [workflow_dispatch]
jobs:
  update-pharmacies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd retriever
          go run .
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add pharmacy.json
          git commit -m updated
          git push origin master
